title: <p align="center"> Karthik Jayaraman </p>
logo: /assets/img/karthik-logo.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/karthikwork/">LinkedIn</a> |
  <a href="https://github.com/karthikjram">GitHub</a>
  <br>   
    High-impact Engineering leader with proven track record in productizing disruptive software & hardware solutions,
    delivering high volume enterprise web services supporting million+ users, from concept to launch
    Enjoyed working at Apple, Microsoft, Intel, HP & Palm.
  <br>
  </p>

theme: jekyll-theme-minimal
